name: Deploy to VPS

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore Pame

      - name: Build
        run: dotnet build Pame --configuration Release --no-restore

      - name: Run tests for Pame.Infrastructure.Test
        run: dotnet test Pame.Infrastructure.Test/Pame.Infrastructure.Test.csproj --no-build --verbosity normal

      - name: Run tests for Pame.Domain.Test
        run: dotnet test Pame.Domain.Test/Pame.Domain.Test.csproj --no-build --verbosity normal

      - name: Run tests for Pame.Application.Test
        run: dotnet test Pame.Application.Test/Pame.Application.Test.csproj --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Publish
        run: dotnet publish Pame.Api/Pame.Api.csproj -c Release -o ./publish

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH }}
          source: "./publish"
          target: "/pagarme"
